Repository vmware/validated-solutions-for-cloud-foundation, pull requests merged in 2022-12, with the labels that each got.

#17 feat: add terraform configurations for CBO
  cbo/terraform-solution-implementation/01-create-role-in-vsphere/main.tf
  cbo/terraform-solution-implementation/01-create-role-in-vsphere/terraform.tfvars.example
  cbo/terraform-solution-implementation/01-create-role-in-vsphere/variables.tf
  cbo/terraform-solution-implementation/01-create-role-in-vsphere/versions.tf
  cbo/terraform-solution-implementation/02-create-folder-in-vsphere/main.tf
  cbo/terraform-solution-implementation/02-create-folder-in-vsphere/terraform.tfvars.example
  cbo/terraform-solution-implementation/02-create-folder-in-vsphere/terraform.tfvars.template
  cbo/terraform-solution-implementation/02-create-folder-in-vsphere/variables.tf
  cbo/terraform-solution-implementation/02-create-folder-in-vsphere/versions.tf
  cbo/terraform-solution-implementation/03-configure-vsphere-permissions/main.tf
  cbo/terraform-solution-implementation/03-configure-vsphere-permissions/terraform.tfvars.example
  cbo/terraform-solution-implementation/03-configure-vsphere-permissions/terraform.tfvars.template
  cbo/terraform-solution-implementation/03-configure-vsphere-permissions/variables.tf
  cbo/terraform-solution-implementation/03-configure-vsphere-permissions/versions.tf
  cbo/terraform-solution-implementation/04-configure-nsx-permissions/main.tf
  cbo/terraform-solution-implementation/04-configure-nsx-permissions/outputs.tf
  cbo/terraform-solution-implementation/04-configure-nsx-permissions/terraform.tfvars.example
  cbo/terraform-solution-implementation/04-configure-nsx-permissions/terraform.tfvars.template
  cbo/terraform-solution-implementation/04-configure-nsx-permissions/variables.tf
  cbo/terraform-solution-implementation/04-configure-nsx-permissions/versions.tf
  cio/README.md
  cio/terraform-solution-implementation/02-vsphere-folders-appliance-management/.gitignore
Labels: enhancement, vvs/cbo

#19 docs(pca): update `README.md`
  pca/README.md
Labels: documentation, dependencies

#20 chore(gh): update `CODEOWNERS`
  .github/CODEOWNERS
  CODEOWNERS
Labels: chore

#18 chore(pca): bump terraform and provider versions
  .github/CODEOWNERS
  CODEOWNERS
  pca/docs/install-terraform-providers/README.md
  pca/terraform-examples/nsxt/nsx-segments-existing/.gitignore
  pca/terraform-examples/nsxt/nsx-segments-existing/versions.tf
  pca/terraform-examples/nsxt/nsx-segments-ondemand/.gitignore
  pca/terraform-examples/nsxt/nsx-segments-ondemand/versions.tf
  pca/terraform-examples/vra/vra-cloud-account/.gitignore
  pca/terraform-examples/vra/vra-cloud-account/versions.tf
  pca/terraform-examples/vra/vra-cloud-template/.gitignore
  pca/terraform-examples/vra/vra-cloud-template/versions.tf
  pca/terraform-examples/vra/vra-content-item/.gitignore
  pca/terraform-examples/vra/vra-content-item/versions.tf
  pca/terraform-examples/vra/vra-content-source/.gitignore
  pca/terraform-examples/vra/vra-content-source/versions.tf
  pca/terraform-examples/vra/vra-fabric-network-existing/.gitignore
  pca/terraform-examples/vra/vra-fabric-network-existing/versions.tf
  pca/terraform-examples/vra/vra-fabric-network-ondemand/.gitignore
  pca/terraform-examples/vra/vra-fabric-network-ondemand/versions.tf
  pca/terraform-examples/vra/vra-flavor-mapping/.gitignore
  pca/terraform-examples/vra/vra-flavor-mapping/versions.tf
  pca/terraform-examples/vra/vra-image-mapping/.gitignore
  pca/terraform-examples/vra/vra-image-mapping/versions.tf
  pca/terraform-examples/vra/vra-network-profile-existing/.gitignore
  pca/terraform-examples/vra/vra-network-profile-existing/versions.tf
  pca/terraform-examples/vra/vra-network-profile-ondemand/.gitignore
  pca/terraform-examples/vra/vra-network-profile-ondemand/versions.tf
  pca/terraform-examples/vra/vra-project/.gitignore
  pca/terraform-examples/vra/vra-project/versions.tf
  pca/terraform-examples/vra/vra-storage-profile/.gitignore
  pca/terraform-examples/vra/vra-storage-profile/versions.tf
  pca/terraform-examples/vsphere/vsphere-content-library-items/.gitignore
  pca/terraform-examples/vsphere/vsphere-content-library-items/versions.tf
  pca/terraform-examples/vsphere/vsphere-content-library-publishing/.gitignore
  pca/terraform-examples/vsphere/vsphere-content-library-publishing/versions.tf
  pca/terraform-examples/vsphere/vsphere-content-library-subscription/.gitignore
  pca/terraform-examples/vsphere/vsphere-content-library-subscription/versions.tf
  pca/terraform-examples/vsphere/vsphere-drs-anti-affinity-rules/.gitignore
  pca/terraform-examples/vsphere/vsphere-drs-anti-affinity-rules/versions.tf
  pca/terraform-examples/vsphere/vsphere-drs-vm-vm-rules/.gitignore
  pca/terraform-examples/vsphere/vsphere-drs-vm-vm-rules/versions.tf
  pca/terraform-examples/vsphere/vsphere-folders-management/.gitignore
  pca/terraform-examples/vsphere/vsphere-folders-management/versions.tf
  pca/terraform-examples/vsphere/vsphere-folders-resource-pool-workload/.gitignore
  pca/terraform-examples/vsphere/vsphere-folders-resource-pool-workload/versions.tf
  pca/terraform-examples/vsphere/vsphere-roles-vrealize/.gitignore
  pca/terraform-examples/vsphere/vsphere-roles-vrealize/versions.tf
Labels: chore, dependencies
